<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        try {

            $sql = "INSERT INTO `countries` (`id`, `phone`, `code`, `name`, `symbol`, `currency`) VALUES
            (1, 93, 'AF', 'Afghanistan', '؋', 'AFN'),
            (2, 358, 'AX', 'Aland Islands', '€', 'EUR'),
            (3, 355, 'AL', 'Albania', 'Lek', 'ALL'),
            (4, 213, 'DZ', 'Algeria', 'دج', 'DZD'),
            (5, 1684, 'AS', 'American Samoa', '$', 'USD'),
            (6, 376, 'AD', 'Andorra', '€', 'EUR'),
            (7, 244, 'AO', 'Angola', 'Kz', 'AOA'),
            (8, 1264, 'AI', 'Anguilla', '$', 'XCD'),
            (9, 672, 'AQ', 'Antarctica', '$', 'AAD'),
            (10, 1268, 'AG', 'Antigua and Barbuda', '$', 'XCD'),
            (11, 54, 'AR', 'Argentina', '$', 'ARS'),
            (12, 374, 'AM', 'Armenia', '֏', 'AMD'),
            (13, 297, 'AW', 'Aruba', 'ƒ', 'AWG'),
            (14, 61, 'AU', 'Australia', '$', 'AUD'),
            (15, 43, 'AT', 'Austria', '€', 'EUR'),
            (16, 994, 'AZ', 'Azerbaijan', 'm', 'AZN'),
            (17, 1242, 'BS', 'Bahamas', 'B$', 'BSD'),
            (18, 973, 'BH', 'Bahrain', '.د.ب', 'BHD'),
            (19, 880, 'BD', 'Bangladesh', '৳', 'BDT'),
            (20, 1246, 'BB', 'Barbados', 'Bds$', 'BBD'),
            (21, 375, 'BY', 'Belarus', 'Br', 'BYN'),
            (22, 32, 'BE', 'Belgium', '€', 'EUR'),
            (23, 501, 'BZ', 'Belize', '$', 'BZD'),
            (24, 229, 'BJ', 'Benin', 'CFA', 'XOF'),
            (25, 1441, 'BM', 'Bermuda', '$', 'BMD'),
            (26, 975, 'BT', 'Bhutan', 'Nu.', 'BTN'),
            (27, 591, 'BO', 'Bolivia', 'Bs.', 'BOB'),
            (28, 599, 'BQ', 'Bonaire, Sint Eustatius and Saba', '$', 'USD'),
            (29, 387, 'BA', 'Bosnia and Herzegovina', 'KM', 'BAM'),
            (30, 267, 'BW', 'Botswana', 'P', 'BWP'),
            (31, 55, 'BV', 'Bouvet Island', 'kr', 'NOK'),
            (32, 55, 'BR', 'Brazil', 'R$', 'BRL'),
            (33, 246, 'IO', 'British Indian Ocean Territory', '$', 'USD'),
            (34, 673, 'BN', 'Brunei Darussalam', 'B$', 'BND'),
            (35, 359, 'BG', 'Bulgaria', 'Лв.', 'BGN'),
            (36, 226, 'BF', 'Burkina Faso', 'CFA', 'XOF'),
            (37, 257, 'BI', 'Burundi', 'FBu', 'BIF'),
            (38, 855, 'KH', 'Cambodia', 'KHR', 'KHR'),
            (39, 237, 'CM', 'Cameroon', 'FCFA', 'XAF'),
            (40, 1, 'CA', 'Canada', '$', 'CAD'),
            (41, 238, 'CV', 'Cape Verde', '$', 'CVE'),
            (42, 1345, 'KY', 'Cayman Islands', '$', 'KYD'),
            (43, 236, 'CF', 'Central African Republic', 'FCFA', 'XAF'),
            (44, 235, 'TD', 'Chad', 'FCFA', 'XAF'),
            (45, 56, 'CL', 'Chile', '$', 'CLP'),
            (46, 86, 'CN', 'China', '¥', 'CNY'),
            (47, 61, 'CX', 'Christmas Island', '$', 'AUD'),
            (48, 672, 'CC', 'Cocos (Keeling) Islands', '$', 'AUD'),
            (49, 57, 'CO', 'Colombia', '$', 'COP'),
            (50, 269, 'KM', 'Comoros', 'CF', 'KMF'),
            (51, 242, 'CG', 'Congo', 'FC', 'XAF'),
            (52, 242, 'CD', 'Congo, Democratic Republic of the Congo', 'FC', 'CDF'),
            (53, 682, 'CK', 'Cook Islands', '$', 'NZD'),
            (54, 506, 'CR', 'Costa Rica', '₡', 'CRC'),
            (55, 225, 'CI', 'Cote D\'Ivoire', 'CFA', 'XOF'),
            (56, 385, 'HR', 'Croatia', 'kn', 'HRK'),
            (57, 53, 'CU', 'Cuba', '$', 'CUP'),
            (58, 599, 'CW', 'Curacao', 'ƒ', 'ANG'),
            (59, 357, 'CY', 'Cyprus', '€', 'EUR'),
            (60, 420, 'CZ', 'Czech Republic', 'Kč', 'CZK'),
            (61, 45, 'DK', 'Denmark', 'Kr.', 'DKK'),
            (62, 253, 'DJ', 'Djibouti', 'Fdj', 'DJF'),
            (63, 1767, 'DM', 'Dominica', '$', 'XCD'),
            (64, 1809, 'DO', 'Dominican Republic', '$', 'DOP'),
            (65, 593, 'EC', 'Ecuador', '$', 'USD'),
            (66, 20, 'EG', 'Egypt', 'ج.م', 'EGP'),
            (67, 503, 'SV', 'El Salvador', '$', 'USD'),
            (68, 240, 'GQ', 'Equatorial Guinea', 'FCFA', 'XAF'),
            (69, 291, 'ER', 'Eritrea', 'Nfk', 'ERN'),
            (70, 372, 'EE', 'Estonia', '€', 'EUR'),
            (71, 251, 'ET', 'Ethiopia', 'Nkf', 'ETB'),
            (72, 500, 'FK', 'Falkland Islands (Malvinas)', '£', 'FKP'),
            (73, 298, 'FO', 'Faroe Islands', 'Kr.', 'DKK'),
            (74, 679, 'FJ', 'Fiji', 'FJ$', 'FJD'),
            (75, 358, 'FI', 'Finland', '€', 'EUR'),
            (76, 33, 'FR', 'France', '€', 'EUR'),
            (77, 594, 'GF', 'French Guiana', '€', 'EUR'),
            (78, 689, 'PF', 'French Polynesia', '₣', 'XPF'),
            (79, 262, 'TF', 'French Southern Territories', '€', 'EUR'),
            (80, 241, 'GA', 'Gabon', 'FCFA', 'XAF'),
            (81, 220, 'GM', 'Gambia', 'D', 'GMD'),
            (82, 995, 'GE', 'Georgia', 'ლ', 'GEL'),
            (83, 49, 'DE', 'Germany', '€', 'EUR'),
            (84, 233, 'GH', 'Ghana', 'GH₵', 'GHS'),
            (85, 350, 'GI', 'Gibraltar', '£', 'GIP'),
            (86, 30, 'GR', 'Greece', '€', 'EUR'),
            (87, 299, 'GL', 'Greenland', 'Kr.', 'DKK'),
            (88, 1473, 'GD', 'Grenada', '$', 'XCD'),
            (89, 590, 'GP', 'Guadeloupe', '€', 'EUR'),
            (90, 1671, 'GU', 'Guam', '$', 'USD'),
            (91, 502, 'GT', 'Guatemala', 'Q', 'GTQ'),
            (92, 44, 'GG', 'Guernsey', '£', 'GBP'),
            (93, 224, 'GN', 'Guinea', 'FG', 'GNF'),
            (94, 245, 'GW', 'Guinea-Bissau', 'CFA', 'XOF'),
            (95, 592, 'GY', 'Guyana', '$', 'GYD'),
            (96, 509, 'HT', 'Haiti', 'G', 'HTG'),
            (97, 0, 'HM', 'Heard Island and Mcdonald Islands', '$', 'AUD'),
            (98, 39, 'VA', 'Holy See (Vatican City State)', '€', 'EUR'),
            (99, 504, 'HN', 'Honduras', 'L', 'HNL'),
            (100, 852, 'HK', 'Hong Kong', '$', 'HKD'),
            (101, 36, 'HU', 'Hungary', 'Ft', 'HUF'),
            (102, 354, 'IS', 'Iceland', 'kr', 'ISK'),
            (103, 91, 'IN', 'India', '₹', 'INR'),
            (104, 62, 'ID', 'Indonesia', 'Rp', 'IDR'),
            (105, 98, 'IR', 'Iran, Islamic Republic of', '﷼', 'IRR'),
            (106, 964, 'IQ', 'Iraq', 'د.ع', 'IQD'),
            (107, 353, 'IE', 'Ireland', '€', 'EUR'),
            (108, 44, 'IM', 'Isle of Man', '£', 'GBP'),
            (109, 972, 'IL', 'Israel', '₪', 'ILS'),
            (110, 39, 'IT', 'Italy', '€', 'EUR'),
            (111, 1876, 'JM', 'Jamaica', 'J$', 'JMD'),
            (112, 81, 'JP', 'Japan', '¥', 'JPY'),
            (113, 44, 'JE', 'Jersey', '£', 'GBP'),
            (114, 962, 'JO', 'Jordan', 'ا.د', 'JOD'),
            (115, 7, 'KZ', 'Kazakhstan', 'лв', 'KZT'),
            (116, 254, 'KE', 'Kenya', 'KSh', 'KES'),
            (117, 686, 'KI', 'Kiribati', '$', 'AUD'),
            (118, 850, 'KP', 'Korea, Democratic People\'s Republic of', '₩', 'KPW'),
            (119, 82, 'KR', 'Korea, Republic of', '₩', 'KRW'),
            (120, 381, 'XK', 'Kosovo', '€', 'EUR'),
            (121, 965, 'KW', 'Kuwait', 'ك.د', 'KWD'),
            (122, 996, 'KG', 'Kyrgyzstan', 'лв', 'KGS'),
            (123, 856, 'LA', 'Lao People\'s Democratic Republic', '₭', 'LAK'),
            (124, 371, 'LV', 'Latvia', '€', 'EUR'),
            (125, 961, 'LB', 'Lebanon', '£', 'LBP'),
            (126, 266, 'LS', 'Lesotho', 'L', 'LSL'),
            (127, 231, 'LR', 'Liberia', '$', 'LRD'),
            (128, 218, 'LY', 'Libyan Arab Jamahiriya', 'د.ل', 'LYD'),
            (129, 423, 'LI', 'Liechtenstein', 'CHf', 'CHF'),
            (130, 370, 'LT', 'Lithuania', '€', 'EUR'),
            (131, 352, 'LU', 'Luxembourg', '€', 'EUR'),
            (132, 853, 'MO', 'Macao', '$', 'MOP'),
            (133, 389, 'MK', 'Macedonia, the Former Yugoslav Republic of', 'ден', 'MKD'),
            (134, 261, 'MG', 'Madagascar', 'Ar', 'MGA'),
            (135, 265, 'MW', 'Malawi', 'MK', 'MWK'),
            (136, 60, 'MY', 'Malaysia', 'RM', 'MYR'),
            (137, 960, 'MV', 'Maldives', 'Rf', 'MVR'),
            (138, 223, 'ML', 'Mali', 'CFA', 'XOF'),
            (139, 356, 'MT', 'Malta', '€', 'EUR'),
            (140, 692, 'MH', 'Marshall Islands', '$', 'USD'),
            (141, 596, 'MQ', 'Martinique', '€', 'EUR'),
            (142, 222, 'MR', 'Mauritania', 'MRU', 'MRO'),
            (143, 230, 'MU', 'Mauritius', '₨', 'MUR'),
            (144, 262, 'YT', 'Mayotte', '€', 'EUR'),
            (145, 52, 'MX', 'Mexico', '$', 'MXN'),
            (146, 691, 'FM', 'Micronesia, Federated States of', '$', 'USD'),
            (147, 373, 'MD', 'Moldova, Republic of', 'L', 'MDL'),
            (148, 377, 'MC', 'Monaco', '€', 'EUR'),
            (149, 976, 'MN', 'Mongolia', '₮', 'MNT'),
            (150, 382, 'ME', 'Montenegro', '€', 'EUR'),
            (151, 1664, 'MS', 'Montserrat', '$', 'XCD'),
            (152, 212, 'MA', 'Morocco', 'DH', 'MAD'),
            (153, 258, 'MZ', 'Mozambique', 'MT', 'MZN'),
            (154, 95, 'MM', 'Myanmar', 'K', 'MMK'),
            (155, 264, 'NA', 'Namibia', '$', 'NAD'),
            (156, 674, 'NR', 'Nauru', '$', 'AUD'),
            (157, 977, 'NP', 'Nepal', '₨', 'NPR'),
            (158, 31, 'NL', 'Netherlands', '€', 'EUR'),
            (159, 599, 'AN', 'Netherlands Antilles', 'NAf', 'ANG'),
            (160, 687, 'NC', 'New Caledonia', '₣', 'XPF'),
            (161, 64, 'NZ', 'New Zealand', '$', 'NZD'),
            (162, 505, 'NI', 'Nicaragua', 'C$', 'NIO'),
            (163, 227, 'NE', 'Niger', 'CFA', 'XOF'),
            (164, 234, 'NG', 'Nigeria', '₦', 'NGN'),
            (165, 683, 'NU', 'Niue', '$', 'NZD'),
            (166, 672, 'NF', 'Norfolk Island', '$', 'AUD'),
            (167, 1670, 'MP', 'Northern Mariana Islands', '$', 'USD'),
            (168, 47, 'NO', 'Norway', 'kr', 'NOK'),
            (169, 968, 'OM', 'Oman', '.ع.ر', 'OMR'),
            (170, 92, 'PK', 'Pakistan', '₨', 'PKR'),
            (171, 680, 'PW', 'Palau', '$', 'USD'),
            (172, 970, 'PS', 'Palestinian Territory, Occupied', '₪', 'ILS'),
            (173, 507, 'PA', 'Panama', 'B/.', 'PAB'),
            (174, 675, 'PG', 'Papua New Guinea', 'K', 'PGK'),
            (175, 595, 'PY', 'Paraguay', '₲', 'PYG'),
            (176, 51, 'PE', 'Peru', 'S/.', 'PEN'),
            (177, 63, 'PH', 'Philippines', '₱', 'PHP'),
            (178, 64, 'PN', 'Pitcairn', '$', 'NZD'),
            (179, 48, 'PL', 'Poland', 'zł', 'PLN'),
            (180, 351, 'PT', 'Portugal', '€', 'EUR'),
            (181, 1787, 'PR', 'Puerto Rico', '$', 'USD'),
            (182, 974, 'QA', 'Qatar', 'ق.ر', 'QAR'),
            (183, 262, 'RE', 'Reunion', '€', 'EUR'),
            (184, 40, 'RO', 'Romania', 'lei', 'RON'),
            (185, 70, 'RU', 'Russian Federation', '₽', 'RUB'),
            (186, 250, 'RW', 'Rwanda', 'FRw', 'RWF'),
            (187, 590, 'BL', 'Saint Barthelemy', '€', 'EUR'),
            (188, 290, 'SH', 'Saint Helena', '£', 'SHP'),
            (189, 1869, 'KN', 'Saint Kitts and Nevis', '$', 'XCD'),
            (190, 1758, 'LC', 'Saint Lucia', '$', 'XCD'),
            (191, 590, 'MF', 'Saint Martin', '€', 'EUR'),
            (192, 508, 'PM', 'Saint Pierre and Miquelon', '€', 'EUR'),
            (193, 1784, 'VC', 'Saint Vincent and the Grenadines', '$', 'XCD'),
            (194, 684, 'WS', 'Samoa', 'SAT', 'WST'),
            (195, 378, 'SM', 'San Marino', '€', 'EUR'),
            (196, 239, 'ST', 'Sao Tome and Principe', 'Db', 'STD'),
            (197, 966, 'SA', 'Saudi Arabia', '﷼', 'SAR'),
            (198, 221, 'SN', 'Senegal', 'CFA', 'XOF'),
            (199, 381, 'RS', 'Serbia', 'din', 'RSD'),
            (200, 381, 'CS', 'Serbia and Montenegro', 'din', 'RSD'),
            (201, 248, 'SC', 'Seychelles', 'SRe', 'SCR'),
            (202, 232, 'SL', 'Sierra Leone', 'Le', 'SLL'),
            (203, 65, 'SG', 'Singapore', '$', 'SGD'),
            (204, 1, 'SX', 'Sint Maarten', 'ƒ', 'ANG'),
            (205, 421, 'SK', 'Slovakia', '€', 'EUR'),
            (206, 386, 'SI', 'Slovenia', '€', 'EUR'),
            (207, 677, 'SB', 'Solomon Islands', 'Si$', 'SBD'),
            (208, 252, 'SO', 'Somalia', 'Sh.so.', 'SOS'),
            (209, 27, 'ZA', 'South Africa', 'R', 'ZAR'),
            (210, 500, 'GS', 'South Georgia and the South Sandwich Islands', '£', 'GBP'),
            (211, 211, 'SS', 'South Sudan', '£', 'SSP'),
            (212, 34, 'ES', 'Spain', '€', 'EUR'),
            (213, 94, 'LK', 'Sri Lanka', 'Rs', 'LKR'),
            (214, 249, 'SD', 'Sudan', '.س.ج', 'SDG'),
            (215, 597, 'SR', 'Suriname', '$', 'SRD'),
            (216, 47, 'SJ', 'Svalbard and Jan Mayen', 'kr', 'NOK'),
            (217, 268, 'SZ', 'Swaziland', 'E', 'SZL'),
            (218, 46, 'SE', 'Sweden', 'kr', 'SEK'),
            (219, 41, 'CH', 'Switzerland', 'CHf', 'CHF'),
            (220, 963, 'SY', 'Syrian Arab Republic', 'LS', 'SYP'),
            (221, 886, 'TW', 'Taiwan, Province of China', '$', 'TWD'),
            (222, 992, 'TJ', 'Tajikistan', 'SM', 'TJS'),
            (223, 255, 'TZ', 'Tanzania, United Republic of', 'TSh', 'TZS'),
            (224, 66, 'TH', 'Thailand', '฿', 'THB'),
            (225, 670, 'TL', 'Timor-Leste', '$', 'USD'),
            (226, 228, 'TG', 'Togo', 'CFA', 'XOF'),
            (227, 690, 'TK', 'Tokelau', '$', 'NZD'),
            (228, 676, 'TO', 'Tonga', '$', 'TOP'),
            (229, 1868, 'TT', 'Trinidad and Tobago', '$', 'TTD'),
            (230, 216, 'TN', 'Tunisia', 'ت.د', 'TND'),
            (231, 90, 'TR', 'Turkey', '₺', 'TRY'),
            (232, 7370, 'TM', 'Turkmenistan', 'T', 'TMT'),
            (233, 1649, 'TC', 'Turks and Caicos Islands', '$', 'USD'),
            (234, 688, 'TV', 'Tuvalu', '$', 'AUD'),
            (235, 256, 'UG', 'Uganda', 'USh', 'UGX'),
            (236, 380, 'UA', 'Ukraine', '₴', 'UAH'),
            (237, 971, 'AE', 'United Arab Emirates', 'إ.د', 'AED'),
            (238, 44, 'GB', 'United Kingdom', '£', 'GBP'),
            (239, 1, 'US', 'United States', '$', 'USD'),
            (240, 1, 'UM', 'United States Minor Outlying Islands', '$', 'USD'),
            (241, 598, 'UY', 'Uruguay', '$', 'UYU'),
            (242, 998, 'UZ', 'Uzbekistan', 'лв', 'UZS'),
            (243, 678, 'VU', 'Vanuatu', 'VT', 'VUV'),
            (244, 58, 'VE', 'Venezuela', 'Bs', 'VEF'),
            (245, 84, 'VN', 'Viet Nam', '₫', 'VND'),
            (246, 1284, 'VG', 'Virgin Islands, British', '$', 'USD'),
            (247, 1340, 'VI', 'Virgin Islands, U.s.', '$', 'USD'),
            (248, 681, 'WF', 'Wallis and Futuna', '₣', 'XPF'),
            (249, 212, 'EH', 'Western Sahara', 'MAD', 'MAD'),
            (250, 967, 'YE', 'Yemen', '﷼', 'YER'),
            (251, 260, 'ZM', 'Zambia', 'ZK', 'ZMW'),
            (252, 263, 'ZW', 'Zimbabwe', '$', 'ZWL')";

            DB::statement($sql);
        } catch (\Throwable $th) {
            
        }
    }
}
